// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4z2_7bJ9HMcMWRTkggUpwUk0RcY_1Ils',
    appId: '1:694781693937:web:bc4822c1060673c23afe50',
    messagingSenderId: '694781693937',
    projectId: 'serious-dating-app-d890b',
    authDomain: 'serious-dating-app-d890b.firebaseapp.com',
    storageBucket: 'serious-dating-app-d890b.firebasestorage.app',
    measurementId: 'G-NQMDCM2L01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFZ-gI5Cy_WXBP3_bokbIEdN4lf417Fs',
    appId: '1:694781693937:android:91b1513f60369b903afe50',
    messagingSenderId: '694781693937',
    projectId: 'serious-dating-app-d890b',
    storageBucket: 'serious-dating-app-d890b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYURzjR4I_TRnO1mzw8kk9UQ5nMI3u3jM',
    appId: '1:694781693937:ios:d4f4d81505e5c1623afe50',
    messagingSenderId: '694781693937',
    projectId: 'serious-dating-app-d890b',
    storageBucket: 'serious-dating-app-d890b.firebasestorage.app',
    iosBundleId: 'com.example.seriousDatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYURzjR4I_TRnO1mzw8kk9UQ5nMI3u3jM',
    appId: '1:694781693937:ios:d4f4d81505e5c1623afe50',
    messagingSenderId: '694781693937',
    projectId: 'serious-dating-app-d890b',
    storageBucket: 'serious-dating-app-d890b.firebasestorage.app',
    iosBundleId: 'com.example.seriousDatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4z2_7bJ9HMcMWRTkggUpwUk0RcY_1Ils',
    appId: '1:694781693937:web:9260e134249e160a3afe50',
    messagingSenderId: '694781693937',
    projectId: 'serious-dating-app-d890b',
    authDomain: 'serious-dating-app-d890b.firebaseapp.com',
    storageBucket: 'serious-dating-app-d890b.firebasestorage.app',
    measurementId: 'G-GMR69L5WB7',
  );

}